server:
  port: ${PORT:8761}
spring:
  application:
    name: FindMovies_EurekaServer
  security:
    user:
      name: admin
      password: ${EUREKA_USER_PASSWORD:password}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/