server:
  port: ${PORT:8761}
security:
  user:
    password: ${eureka.password}
spring:
  application:
    name: FindMovies_EurekaServer
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}